# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.4"
  - "3.3"
  - "2.7"
  - "2.6"
  - "pypy"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -r requirements.txt

# command to run tests, e.g. python setup.py test
# TODO 
#script: python setup.py test
# Travis is complaining about no override script key
# so here's a simple one until i get some tests in
script: python -c "import sys; sys.exit(0)"
